name: BucketOfLua
main: im.creep.bucketoflua.BucketOfLuaPlugin
version: r1-alpha1
commands:
   lua:
      description: Primary Lua command center
      usage: |
         /lua - entry point for BucketOfLua administrative commands.
         Following commands may be interesting:
           /lua run - starts all Lua scripts.
           /lua stop - stops all Lua scripts.
           /lua reset - resets Lua subsystem.
